public class TemperaturaTest {
	public static void main(String[] args) {
		System.out.println();
		System.out.println("Test case 1: costruttore di default constructor e metodo scriviOutput()");
		System.out.println();
		Temperatura t1 = new Temperatura();
		System.out.println("Risultato costruttore di default:");
		System.out.println("Verifica 0 gradi C.");
		System.out.println();
		t1.scriviOutput();
		System.out.println();
		System.out.println("==========================================");

		System.out.println("Test case 2: metodo leggiInput().");
		t1.leggiInput();
		System.out.println();
		System.out.println("Verifica temperatura e unita':");
		System.out.println("Dovrebbe essere quello che e' stato inserito.");
		System.out.println();
		t1.scriviOutput();
		System.out.println();
		System.out.println("==========================================");

		System.out.println("Test case 3: costruttore con solo la temperatura.");
		Temperatura t2 = new Temperatura(20.5);
		System.out.println();
		System.out.println("Verifica 20.5 gradi C.");
		System.out.println();
		t2.scriviOutput();
		System.out.println();
		System.out.println("==========================================");

		System.out.println("Test case 4: costruttore con solo l'unita', f.");
		System.out.println();
		System.out.println("Verifica 0 gradi f.");
		System.out.println();
		Temperatura t3 = new Temperatura('f');
		t3.scriviOutput();
		System.out.println();
		System.out.println("==========================================");

		System.out.println("Test case 5:  costruttore con solo l'unita', c.");
		System.out.println();
		System.out.println("Verifica 0 gradi c.");
		System.out.println();
		Temperatura t4 = new Temperatura('c');
		t4.scriviOutput();
		System.out.println();
		System.out.println("==========================================");

		System.out.println("Test case 6:  costruttore con temperatura e unita'.");
		System.out.println();
		System.out.println("Verifica -51.2 gradi F.");
		System.out.println();
		Temperatura t5 = new Temperatura(-51.2, 'F');
		t5.scriviOutput();
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 7: gradi originali in C e li stampa in C.");
		System.out.println();
		System.out.println("Verifica -46.2 gradi Celsius.");
		System.out.println();
		t5.scriviC();
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 8: gradi originali in F e li stampa in C.");
		System.out.println();
		System.out.println("Verifica 0 gradi Celsius.");
		System.out.println();
		t4.scriviC();
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 9: gradi originali in C e li stampa in F.");
		System.out.println();
		System.out.println("Verifica 32 gradi Fahrenheit");
		System.out.println();
		t4.scriviF();
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 10: gradi originali in F e li stampa in F.");
		System.out.println();
		System.out.println("Verifica -51.2 gradi Fahrenheit");
		System.out.println();
		t5.scriviF();
		System.out.println();
		System.out.println("Premi enter per continuare.");
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 11: getF con gradi originali in F.");
		System.out.println();
		System.out.println("Verifica -51.2");
		System.out.println();
		System.out.println(t5.getF());
		System.out.println();
		System.out.println("Premi enter per continuare.");
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 12: getF con gradi originali in C.");
		System.out.println("Verifica 32");
		System.out.println();
		System.out.println(t4.getF());
		System.out.println();
		System.out.println("Premi enter per continuare.");
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 13: getC con gradi originali in F.");
		System.out.println("Verifica -46.2");
		System.out.println();
		System.out.println(t5.getC());
		System.out.println();
		System.out.println("Premi enter per continuare.");
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 14: getC con gradi originali in C.");
		System.out.println("Verifica 0");
		System.out.println();
		System.out.println(t4.getC());
		System.out.println();
		System.out.println("Premi enter per continuare.");
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 15: metodi set per entrambi gli attributi.");
		System.out.println("t5 before:");
		t5.scriviOutput();
		t5.set(72.8, 'C');
		System.out.println("After set: Verifica 72.8 gradi C.");
		System.out.println();
		t5.scriviOutput();
		System.out.println();
		System.out.println("Premi enter per continuare.");
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 16: metodo set per la sola temperatura.");
		System.out.println("t5 prima:");
		t5.scriviOutput();
		t5.set(100, 'C');
		System.out.println("Dopo set: Verifica 100 gradi C.");
		System.out.println();
		t5.scriviOutput();
		System.out.println();
		System.out.println("Premi enter per continuare.");
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 17:  metodo set per la sola unita'.");
		System.out.println("t5 prima:");
		t5.scriviOutput();
		t5.set('F');
		System.out.println("Dopo set: Verifica 100 gradi F.");
		System.out.println();
		t5.scriviOutput();
		System.out.println();
		System.out.println("Premi enter per continuare.");
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 18: equals 1.");
		System.out.println();
		t1.set(100, 'C');
		t2.set(212, 'F');
		System.out.println("T1 = 100 gradi C.");
		System.out.println("T2 = 212 gradi F.");
		System.out.println();
		System.out.println("Ecco le due temperature converted to gradi C:");
		t1.scriviC();
		t2.scriviC();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere vero.");
		System.out.println();
		System.out.println(t1.equals(t2));
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 19: equals 2.");
		System.out.println();
		t1.set(100.1);
		System.out.println("T1 changed to 100.1 gradi C.");
		System.out.println("T2 = 212 gradi F.");
		System.out.println();
		System.out.println("Ecco le due temperature in gradi C:");
		t1.scriviC();
		t2.scriviC();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere falso.");
		System.out.println();
		System.out.println(t1.equals(t2));
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 20: equals 3.");
		System.out.println();
		t1.set(100);
		t2.set(212.1);
		System.out.println("T1 riportata a 100 gradi C.");
		System.out.println("T2 = 212.1 gradi F.");
		System.out.println();
		System.out.println("Ecco le due temperature in gradi C:");
		t1.scriviC();
		t2.scriviC();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere falso.");
		System.out.println();
		System.out.println(t1.equals(t2));
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 21: maggioreDi 1.");
		System.out.println();
		t1.set(100, 'C');
		t2.set(212, 'F');
		System.out.println("T1 = 100 gradi C.");
		System.out.println("T2 = 212 gradi F.");
		System.out.println();
		System.out.println("Ecco le due temperature converted to gradi C:");
		t1.scriviC();
		t2.scriviC();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere falso.");
		System.out.println();
		System.out.println(t1.maggioreDi(t2));
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 22: maggioreDi 2.");
		System.out.println();
		t1.set(100.1);
		System.out.println("T1 cambiata in 100.1 gradi C.");
		System.out.println("T2 = 212 gradi F.");
		System.out.println();
		System.out.println("Ecco le due temperature in gradi C:");
		t1.scriviC();
		t2.scriviC();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere vero.");
		System.out.println();
		System.out.println(t1.maggioreDi(t2));
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 23: maggioreDi 3.");
		System.out.println();
		t1.set(100);
		t2.set(212.1);
		System.out.println("T1 riportata a 100 gradi C.");
		System.out.println("T2 = 212.1 gradi F.");
		System.out.println();
		System.out.println("Ecco le due temperature in gradi C:");
		t1.scriviC();
		t2.scriviC();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere falso.");
		System.out.println();
		System.out.println(t1.maggioreDi(t2));
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 24: minoreDi 1.");
		System.out.println();
		t1.set(100, 'C');
		t2.set(212, 'F');
		System.out.println("T1 = 100 gradi C.");
		System.out.println("T2 = 212 gradi F.");
		System.out.println();
		System.out.println("Ecco le due temperature converted to gradi C:");
		t1.scriviC();
		t2.scriviC();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere falso.");
		System.out.println();
		System.out.println(t1.minoreDi(t2));
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 25: minoreDi 2.");
		System.out.println();
		t1.set(100.1);
		System.out.println("T1 cambiata in 100.1 gradi C.");
		System.out.println("T2 = 212 gradi F.");
		System.out.println();
		System.out.println("Ecco le due temperature in gradi C:");
		t1.scriviC();
		t2.scriviC();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere falso.");
		System.out.println();
		System.out.println(t1.minoreDi(t2));
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test case 26: minoreDi 3.");
		System.out.println();
		t1.set(100);
		t2.set(212.1);
		System.out.println("T1 riportata a 100 gradi C.");
		System.out.println("T2 = 212.1 gradi F.");
		System.out.println();
		System.out.println("Ecco le due temperature in gradi C:");
		t1.scriviC();
		t2.scriviC();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere vero.");
		System.out.println();
		System.out.println(t1.minoreDi(t2));
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test Case 27: 0 gradi C e' = a 32 gradi F?");
		System.out.println();
		t1.set(0, 'C');
		t2.set(32, 'F');
		System.out.println("Ecco le due temperature:");
		System.out.println();
		t1.scriviOutput();
		t2.scriviOutput();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere vero.");
		System.out.println();
		System.out.println(t1.equals(t2));
		System.out.println();
		System.out.println("==========================================");

		System.out.println();
		System.out.println("Test Case 28: -40 gradi C e' = a -40 gradi F?");
		System.out.println();
		t1.set(-40, 'C');
		t2.set(-40, 'F');
		System.out.println("Ecco le due temperature:");
		System.out.println();
		t1.scriviOutput();
		t2.scriviOutput();
		System.out.println();
		System.out.println("Verifica: dovrebbe essere vero.");
		System.out.println();
		System.out.println(t1.equals(t2));
		System.out.println();
	}
}
